import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen w-full bg-background`}
      >
        <header className="max-w-7xl mx-auto w-full p-4">
          <h1 className="text-4xl font-bold mb-2">
            Графіки відключень електроенергії в м. Запоріжжя
          </h1>
          <p className="">Real-time monitoring of 12 distribution queues</p>
        </header>

        <main className="flex-1">{children}</main>

        <footer className="max-w-7xl mx-auto w-full p-4">footer</footer>
      </body>
    </html>
  );
}
